name: sjq
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.0
  macos_ui: ^2.0.5
  image_picker:
  google_fonts: ^6.2.1
  table_calendar: ^3.0.9
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
    - assets/avatar/
    - assets/data/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

