// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkytJ9D5zSsg_Yd77gjzxPULFNQTvIHyc',
    appId: '1:174331654904:web:b2f8f31a2f5dcca61fc10d',
    messagingSenderId: '174331654904',
    projectId: 'nutrivision-8876b',
    authDomain: 'nutrivision-8876b.firebaseapp.com',
    storageBucket: 'nutrivision-8876b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwklBY2lLxIHl1SzVrWsWi__dW1zw63xE',
    appId: '1:174331654904:android:41cb31801b6e41f61fc10d',
    messagingSenderId: '174331654904',
    projectId: 'nutrivision-8876b',
    storageBucket: 'nutrivision-8876b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcV1X8XO5KZRMtJHvDaDCcg81vm-w1zuA',
    appId: '1:174331654904:ios:c395e4eed91c16031fc10d',
    messagingSenderId: '174331654904',
    projectId: 'nutrivision-8876b',
    storageBucket: 'nutrivision-8876b.appspot.com',
    iosBundleId: 'com.example.dataPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcV1X8XO5KZRMtJHvDaDCcg81vm-w1zuA',
    appId: '1:174331654904:ios:c395e4eed91c16031fc10d',
    messagingSenderId: '174331654904',
    projectId: 'nutrivision-8876b',
    storageBucket: 'nutrivision-8876b.appspot.com',
    iosBundleId: 'com.example.dataPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkytJ9D5zSsg_Yd77gjzxPULFNQTvIHyc',
    appId: '1:174331654904:web:127ad567a9c4786b1fc10d',
    messagingSenderId: '174331654904',
    projectId: 'nutrivision-8876b',
    authDomain: 'nutrivision-8876b.firebaseapp.com',
    storageBucket: 'nutrivision-8876b.appspot.com',
  );

}